### ISSUE TITLE
git submodule dependency

### ISSUE THREAD

**Issue by cherryland** [envoyproxy/envoy-filter-example#119]
As a Bazel user I would expect to download the envoy source code by using a Bazel repository rule. 

Example

```sh
http_archive(
    name = "envoy",
    sha256 = "d7e270cd02923eee34d6fc5bfc1e73541e1c3121813779f779d29112402d2ecc",
    strip_prefix = "envoy-1.13.1",
    url = "https://github.com/envoyproxy/envoy/archive/v1.13.1.tar.gz",
)
```

The build **fails** when trying to make envoy available for binding by using the [http_archive](https://docs.bazel.build/versions/master/repo/http.html) rule to download the Bazel repository as a compressed archive file. 

What is the technical reason behind the strict git submodule dependency, besides the reliance on the envoy's [.bazelrc](https://github.com/envoyproxy/envoy-filter-example/blob/master/.bazelrc) Bazel configuration file.

@htuch @mattklein123 @dio @alyssawilk @PiotrSikora

**Comment by htuch** [comment]
You're correct in noting that files like `.bazelrc` are fairly important to making Envoy build correctly. We mainly use submodules in the Envoy filter example repo because it matches the use of Envoy at some known Envoy depoyments.

What build error are you seeing?

**Comment by cherryland** [comment]
Thanks @htuch. I got the example working by using the [git_repository](https://docs.bazel.build/versions/master/repo/git.html) rule and the latest commit hash from the submodule definition

```sh
git_repository(
    name = "envoy",
    commit = "<hash>",
    remote = "https://github.com/envoyproxy/envoy.git",
)
```
