### ISSUE TITLE
build error gcc: error trying to exec '/usr/lib/gcc/x86_64-linux-gnu/7/cc1plus': execv: Argument list too long

### ISSUE THREAD

**Issue by helight** [envoyproxy/envoy-filter-example#132]
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/3577de60e542174ece7fd3dd4ebef4be/external/envoy/source/exe/BUILD:58:17: C++ compilation of rule
 '@envoy//source/exe:main_common_lib' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wa
ll -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 1321 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error trying to exec '/usr/lib/gcc/x86_64-linux-gnu/7/cc1plus': execv: Argument list too long
Target //:envoy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.670s, Critical Path: 4.08s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by taoyuanyuan** [comment]
please how to solve it?

**Comment by taoyuanyuan** [comment]
@helight  thank you

**Comment by helight** [comment]
> please how to solve it?

1. upgrade gcc to 9 or later 
2. clang 10 or later, and this work to me.

**Comment by eugy-scroodgee** [comment]
Hello, I have the same issue, but gcc and clang both 10th versions. Is this problem really caused by the old version of the build tools?

**Comment by helight** [comment]
clang 10 or later will be ok

**Comment by eugy-scroodgee** [comment]
Thanks for the quick reply, but I have clang 10 installed already.
