### ISSUE TITLE
envoy-filter-example build failed 

### ISSUE THREAD

**Issue by bryanwux** [envoyproxy/envoy-filter-example#155]
I got the following failure message when I build envoy-filter-example with latest envoy.
```
ERROR: --platform_mappings was set to 'bazel/platform_mappings' but no such file exists relative to the package path roots, '[/root/envoy-filter-example]'
INFO: Elapsed time: 7.780s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
```

When I look into this, I find this recently merged PR https://github.com/envoyproxy/envoy/pull/20813 causes this issue because envoy-filter-example/bazel/platform_mappings is missing while this file is needed by envoy-filter-example/envoy/.bazelrc by `build --platform_mappings=bazel/platform_mappings`. 

So I suggest add platform_mappings to avoid this build failure.

**Comment by phlax** [comment]
it looks like this should be set up for the filter example:

```console

$ git grep platform_mapp
.bazelrc:build --platform_mappings=bazel/platform_mappings
ci/filter_example_setup.sh:ln -sf "${ENVOY_SRCDIR}"/bazel/platform_mappings "${ENVOY_FILTER_EXAMPLE_SRCDIR}"/bazel/

```

not sure why it is failing to build in your env

cc @keith

**Comment by bryanwux** [comment]
> it looks like this should be set up for the filter example:
> 
> ```
> $ git grep platform_mapp
> .bazelrc:build --platform_mappings=bazel/platform_mappings
> ci/filter_example_setup.sh:ln -sf "${ENVOY_SRCDIR}"/bazel/platform_mappings "${ENVOY_FILTER_EXAMPLE_SRCDIR}"/bazel/
> ```
> 
> not sure why it is failing to build in your env
> 
> cc @keith

**Comment by bryanwux** [comment]
> it looks like this should be set up for the filter example:
> 
> ```
> $ git grep platform_mapp
> .bazelrc:build --platform_mappings=bazel/platform_mappings
> ci/filter_example_setup.sh:ln -sf "${ENVOY_SRCDIR}"/bazel/platform_mappings "${ENVOY_FILTER_EXAMPLE_SRCDIR}"/bazel/
> ```
> 
> not sure why it is failing to build in your env
> 
> cc @keith

To reproduce this issue: 
```
cd ~/envoy-filter-example
git submodule update --init
bazel build //http-filter-example:envoy
```
I am not sure why the symlink is not working.

**Comment by keith** [comment]
https://github.com/envoyproxy/envoy-filter-example/pull/157

**Comment by alecholmez** [comment]
One way to fix this is by just sym link `envoy/bazel`

I got around it that way. Similar to how the .devcontainer is linked

**Comment by mkauf** [comment]
Another way to fix this bug:
```
ln -s ../envoy/bazel/platform_mappings bazel/platform_mappings
```
