### ISSUE TITLE
 C++ compilation error during build

### ISSUE THREAD

**Issue by SurajMenon** [envoyproxy/envoy-filter-example#21]
While trying the steps mentioned in https://github.com/lyft/envoy-filter-example/tree/master/http-filter-example, the build(bazel build //http-filter-example:envoy) gives a compilation error on mac:
 
> C++ compilation of rule '@envoy//source/common/router:config_lib' failed .

Following is the exception in detail:

>ERROR: >/private/var/tmp/_bazel_smenon2/8057895bf9b56d918b0676d518f20623/external/envoy/source/>common/router/BUILD:11:1: C++ compilation of rule '@envoy//source/common/router:config_lib' >failed (Exit 1).
>external/envoy/source/common/router/config_impl.cc:562:64: error: default initialization of an >object of const type 'const VirtualHostImpl::CatchAllVirtualCluster' without a user-provided default >constructor
>const VirtualHostImpl::CatchAllVirtualCluster VirtualHostImpl::VIRTUAL_CLUSTER_CATCH_ALL;
>                                                               ^
>                                                                                       {}
>external/envoy/source/common/router/config_impl.cc:563:39: error: default initialization of an >object of const type 'const Envoy::Router::SslRedirector' without a user-provided default >constructor
>const SslRedirector SslRedirectRoute::SSL_REDIRECTOR;

Do let me know if you think I might be doing something wrong.

**Comment by htuch** [comment]
Can you provide compiler/toolchain information? Thanks.

**Comment by mattklein123** [comment]
Per @htuch please make sure you have the right version of xcode documented here: https://github.com/lyft/envoy/tree/master/bazel#quick-start-bazel-build-for-developers

**Comment by SurajMenon** [comment]
@htuch The issue persisted even after using xcode 8.3.3

**Comment by htuch** [comment]
@SurajMenon Check out https://github.com/lyft/envoy/blob/master/ci/README.md#building-and-running-tests-as-a-developer for how to work with Envoy in the Docker image used by CI, which does basically what you are after.

I can't replicate this as a I build on Linux. I suspect it's a compiler too new/old issue. I know we hit these missing-default-constructor issues internally in Google with some compilers that are too new. Does adding a default constructor to `SslRedirector` fix?

**Comment by mattklein123** [comment]
Closing out as answered.
