### ISSUE TITLE
Bazel build error when using lyft/envoy-build:latest and CI scripts

### ISSUE THREAD

**Issue by PatrickAuld** [envoyproxy/envoy-filter-example#23]
I'm attempting to build Envoy and test the example filter but keep hitting the same build issue. I first encountered this attempting to run Bazel on Mac but I can reproduce it using the Docker build container as well. I've gone though the [quick-start-bazel-build-for-developers](https://github.com/lyft/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers) locally and also tried the CI build described [here](https://github.com/envoyproxy/envoy/tree/master/ci#building-and-running-tests-as-a-developer) but the command `./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'` also fails. 

This issue uses directions in both this repo and the envoy main repo, if it should be moved there let me know.

CI run error:
```
› ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.dev'
Unable to find image 'lyft/envoy-build:b3542cdfe76e7e46c276c781935d339d4ecd0502' locally
b3542cdfe76e7e46c276c781935d339d4ecd0502: Pulling from lyft/envoy-build
<snip>
Cloning into '/build/envoy-filter-example'...
remote: Counting objects: 73, done.
remote: Total 73 (delta 0), reused 0 (delta 0), pack-reused 73
Unpacking objects: 100% (73/73), done.
Checking connectivity... done.
Note: checking out 'b904b8ce9cabafb485e6b6fae1d0fd9e33ddfcc1'.
<snip>
HEAD is now at b904b8c... filters: remove deprecated type(). (#19)
building using 4 CPUs
clang-5.0/clang++-5.0 toolchain configured
bazel fastbuild build with tests...
Building...
INFO: $TEST_TMPDIR defined: output root default is '/build/tmp'.
Extracting Bazel installation...
INFO: Analysed target //source/exe:envoy-static (83 packages loaded).
INFO: Found 1 target...
ERROR: Process exited with status 1: Process exited with status 1
fatal: Not a git repository: ../.git/modules/envoy
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 46.147s, Critical Path: 0.11s
FAILED: Build did NOT complete successfully
```

When running the Bazel command directly on the build image the issue also occurs. The issue remains if I don't mount `/root/.cache/bazel` into the host's `/tmp/` as well. The Docker image of `lyft/envoy-build:latest` was pulled today.

   ```
› docker run -v /tmp/bazel_cache:/root/.cache/bazel -v pwd:/envoy-filter-example -w /envoy-filter-example -it lyft/envoy-build:latest bazel build //:envoy
.
External dependency cache directory /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
make: Entering directory '/root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy_deps'
make: '/root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep' is up to date.
<snip>

real	0m0.099s
user	0m0.000s
sys	0m0.000s
DEBUG: /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy/bazel/repositories.bzl:18:5: Fetching external dependencies...
DEBUG: /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy/bazel/repositories.bzl:24:5:
DEBUG: /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy/bazel/repositories.bzl:25:5: External dependency cache directory /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
make: Entering directory '/root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy_deps'
make: '/root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep' is up to date.
<snip>

real	0m0.099s
user	0m0.000s
sys	0m0.000s
DEBUG: /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy/bazel/repositories.bzl:26:5: External dep build exited with return code: 0
ERROR: in target '//external:cc_toolchain': error loading package '@local_config_cc//': Extension file not found. Unable to load file '@local_config_cc//:dummy_toolchain.bzl': file doesn't exist or isn't a file
INFO: Elapsed time: 3.278s
FAILED: Build did NOT complete successfully (4 packages loaded)
    currently loading: @local_config_cc// ... (2 packages)
```

**Comment by mattklein123** [comment]
@htuch any idea on this one? Does something need to get updated due to all the recent changes?

**Comment by htuch** [comment]
The second set of errors (in particular `RROR: in target '//external:cc_toolchain': error loading package '@local_config_cc//': Extension file not found. Unable to load file '@local_config_cc//:dummy_toolchain.bzl': file doesn't exist or isn't a file`, from Bazel command directly leads me to think that either the version of Bazel is not 0.7.0 (check with `bazel version`), which is the minimum we require. Also please try `bazel clean --expunge`.

**Comment by PatrickAuld** [comment]
This ended up being partly user error; XCode failed to install via the App Store and I didn't notice. Once everything was installed correctly I am able to build Envoy in its _own repo_ on `master` on my Mac. I can not build it from this repo and its submodule however.

I did do the `git submodule update --init` command before building previously. My bazel version is `0.7.0-homebrew`.

This is the error I now see when executing `bazel build //:envoy` from this repo on Mac 10.12.6. In case the error message wasn't actually an error in the build I also tried running the tests with `bazel test //:echo2_integration_test` and the same message is printed.

```
<snip>
Successful build of /private/var/tmp/_bazel_pauld/c2567331cc76560540bcdae4d8ac7636/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/protobuf.dep
.
DEBUG: /private/var/tmp/_bazel_pauld/c2567331cc76560540bcdae4d8ac7636/external/envoy/bazel/repositories.bzl:26:5: External dep build exited with return code: 2.
DEBUG: /private/var/tmp/_bazel_pauld/c2567331cc76560540bcdae4d8ac7636/external/envoy/bazel/repositories.bzl:28:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/lyft/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
ERROR: error loading package '': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_bzl//': no such package '@envoy_deps//thirdparty/protobuf': External dep build failed.
INFO: Elapsed time: 116.919s
```

I updated the `envoy` submodule to master (3f57cae48877fcc960f8b06994e324ed25a41b64) and got a new error:

```
> bazel build //:envoy
ERROR: /private/var/tmp/_bazel_pauld/c2567331cc76560540bcdae4d8ac7636/external/envoy/bazel/repositories.bzl:214:3: no such package '@com_github_fmtlib_fmt//': Unable to load package for //bazel/external:fmtlib.BUILD: not found. and referenced by '//external:fmtlib'.
ERROR: Analysis of target '//:envoy' failed; build aborted: Loading failed.
INFO: Elapsed time: 0.114s
```

I updated the submodule to the `v1.4.0` tag and got yet a different error. This is getting long so [here is a Gist](https://gist.github.com/PatrickAuld/fae9487b5f6a0fed55a26522fa4d63e3) of it. Its a compile error in `boringssl`. I did a `bazel clean --expunge` and reran the build to verify things and the same error happens.

**Comment by karolz-ms** [comment]
I have the same issue except the error is, for some reason, different

```
root@c5139611f8f8:/code/envoy-filter-example# bazel build //:envoy
............
ERROR: /root/.cache/bazel/_bazel_root/10680e8ee3273e72f1d320dfcf6be48e/external/envoy/bazel/repositories.bzl:257:3: no such package '@com_github_gabime_spdlog//': Unable to load package for //bazel/external:spdlog.BUILD: not found. and referenced by '//external:spdlog'
ERROR: Analysis of target '//:envoy' failed; build aborted: Loading failed
INFO: Elapsed time: 3.257s
FAILED: Build did NOT complete successfully (15 packages loaded)
```

I did update the submodule to one of today's commits (https://github.com/karolz-ms/envoy-filter-example/commit/15f68771a5a8b69b6414c3672cd2f63edcf6d9fc), have run `git submodule update --init` and `basel clean --expunge`... no luck. Using `lyft/envoy-build:latest` to build.

Please help--thx!

**Comment by PatrickAuld** [comment]
Oddly I get a different error when using the `lyft/envoy-build:latest` docker image.

```
in envoy-filter-example/ on master
› docker run -v /tmp/bazel_cache:/root/.cache/bazel -v `pwd`:/envoy-filter-example -w /envoy-filter-example -it lyft/envoy-build:latest bazel build //:envoy
.
ERROR: /root/.cache/bazel/_bazel_root/2689a15d13c8176e302c46da5aa07874/external/envoy/bazel/repositories.bzl:214:3: no such package '@com_github_fmtlib_fmt//': Unable to load package for //bazel/external:fmtlib.BUILD: not found. and referenced by '//external:fmtlib'
ERROR: Analysis of target '//:envoy' failed; build aborted: Loading failed
INFO: Elapsed time: 7.504s
FAILED: Build did NOT complete successfully (15 packages loaded)
```

**Comment by karolz-ms** [comment]
@PatrickAuld I have seen this one too, but only once. After `basel clean` I started seeing the one I quoted above. Go figure...

**Comment by htuch** [comment]
I can repeat this, will fix.

**Comment by karolz-ms** [comment]
Thanks @htuch appreciate quick resolution. Things are looking good on my side now.
