### ISSUE TITLE
Unable to build the filter example

### ISSUE THREAD

**Issue by shishir127** [envoyproxy/envoy-filter-example#38]
Followed the directions for [building the example filter](https://github.com/envoyproxy/envoy-filter-example#building) but I keep getting this error. I'm trying to build on OS X El Capitan and I've made sure I have the latest version of all [dependencies listed](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers).

> 3 warnings generated.
> mv -f src/tests/.deps/tcm_min_asserts_unittest-tcmalloc_unittest.Tpo src/tests/.deps/tcm_min_asserts_unittest-tcmalloc_unittest.Po
> 
> real	0m28.083s
> user	0m46.548s
> sys	0m9.496s
> make: *** [/private/var/tmp/_bazel_shishir/0eafc979d803d3fb03e26d0005f3ec89/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep] Error 1
> .
> DEBUG: /private/var/tmp/_bazel_shishir/0eafc979d803d3fb03e26d0005f3ec89/external/envoy/bazel/repositories.bzl:84:5: External dep build exited with return code: 2.
> DEBUG: /private/var/tmp/_bazel_shishir/0eafc979d803d3fb03e26d0005f3ec89/external/envoy/bazel/repositories.bzl:86:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
> ERROR: /private/var/tmp/_bazel_shishir/0eafc979d803d3fb03e26d0005f3ec89/external/envoy/bazel/repositories.bzl:167:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'.
> ERROR: Analysis of target '//:envoy' failed; build aborted.
> INFO: Elapsed time: 28.793s
> 

Can someone help me with resolving this please.

**Comment by alyssawilk** [comment]
@zuercher any ideas?

**Comment by zuercher** [comment]
Have you been able to build bazel separately from the filter example? It looks to me that the version of envoy specified as a submodule in envoy-filter-example is just old enough not to work with bazel 0.10 (for me bazel errors out immediately with an error message that I recognize as occurring when one tries to build envoy with an older version of bazel).

I updated the envoy version to head of master (envoyproxy/envoy@38d82715) locally and it seems to build correctly.

In any event, there should be a file ending in "gperftools.dep.log" referenced in the build output that has the actual errors that occurred while trying to build that dependency.

**Comment by shishir127** [comment]
@zuercher I'm using bazel for the first time, so I don't know what building bazel separately means. Is there some documentation/guide somewhere that I can refer to? BTW I'm using bazel 0.10.1.

I also updated envoy to the latest commit that you mentioned and tried building it locally, but I get the error `ERROR: in target '//external:cc_toolchain': no such package '@local_config_cc//': too many (2) positional arguments in call to configure_osx_toolchain(repository_ctx).`

I also tried to build it using the envoy-build image envoyproxy/envoy-build:38d827159d5d54db20bf83734df06c90fc3fea9b. But I got this error 

> Successful build of /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep
> Successful build of /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep
> DEBUG: /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy/bazel/repositories.bzl:76:5: Fetching external dependencies...
> DEBUG: /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy/bazel/repositories.bzl:82:5:
> DEBUG: /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy/bazel/repositories.bzl:83:5: Timed out; also encountered an error while attempting to retrieve output
> DEBUG: /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy/bazel/repositories.bzl:84:5: External dep build exited with return code: 256
> DEBUG: /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy/bazel/repositories.bzl:86:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
> ERROR: /root/.cache/bazel/_bazel_root/293f7969b9b501b0ce20c5674b034528/external/envoy/bazel/repositories.bzl:169:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'
> ERROR: Analysis of target '//:envoy' failed; build aborted: Loading failed
> INFO: Elapsed time: 758.416s
> FAILED: Build did NOT complete successfully (105 packages loaded)

Can you also let me know how you have set up your local environment? Any documentation/guides I can follow for that? I followed the [documentation](https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers), is there anything else that I have to do?

**Comment by zuercher** [comment]
Sorry, I meant building envoy separately -- e.g. cloning it directly and building there.

The bazel error `too many (2) positional arguments in call to configure_osx_toolchain(repository_ctx)` is indicative of trying to compile a version of  envoy (95ee420c379942fd692b42c84a1fd5ef4d7035ec or later) with bazel 0.9 (or earlier).

Building current master with bazel 0.10.1 works for me. I have xcode 9.2 installed:
```
$ cc -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
The CI build is using Xcode 8.3, so it should work there as well.

The envoy-build image looks to have timed out downloading the gperftools source.

**Comment by zuercher** [comment]
Were you ever able to get this working?

**Comment by shishir127** [comment]
No I wasn't. Will close those issue.
