### ISSUE TITLE
build process consistency (dev-tooling)

### ISSUE THREAD

**Issue by chopmann** [envoyproxy/envoy-filter-example#55]
I know it's an example project, but after fighting a bit with bazel or more so (ccache and fedora 28) and almost giving up, I went to the "main repo" and had a look at the docs and because you folks are so nice, there are bunch of Images + scripts that wrap away all the nastiness of dependencies and tooling. 

One just needs 
https://github.com/envoyproxy/envoy/blob/master/ci/run_envoy_docker.sh
https://github.com/envoyproxy/envoy/blob/master/ci/envoy_build_sha.sh
copy the binary out of bazel-bin to a mount point and you are set. 

I know keeping this in sync with the main project is a Sisyphus work and it doenst have to be the fully fledged dev loving tooling like https://github.com/envoyproxy/envoy/tree/master/ci, but those 2 scripts get you started really quick. Is actually doing what .circleci/config.yaml does but for devs.

I know nothing about bazel, but the scripts are not that complex. Might learn a thing or two on the way The build dir is not being used and I have to copy the binary out of bazel-bin before leaving the container. The bazel-dir is not working on the host due to symlinks, but that's not that awful. I'll give a go this weekend.

**Comment by sirajmansour** [comment]
It would be awesome to get some out of the box IDE support like visual studio for people (like me) who are not familiar with bazel builds and C++ development.

**Comment by robertpanzer** [comment]
:+1: 
It would be nice to get some instructions on how to get started with an IDE.
Instead of looking at the filter implementation itself, I am spending all my time on Bazel and it's IDE support.
I know many folks can probably code C++ without any support from the IDE like resolving names, types, etc, but for me this is really frustrating.
It would be great to have a section in a readme to get started with CLion or VSCode.
(In Clion the Bazel plugin doesn't seem to properly synchronize the Envoy module, in VS code I seem to be unable to build with debug info and always have to build in a separate terminal)

**Comment by jmarantz** [comment]
@oschaaf who has been using VSCode with Envoy. He might be able to shed some pointers.

 I like this idea quite a bit even though I don't usually use IDEs. I think the use of deeply nested namespaces with lots of names existing in multiple namespaces makes the codebase challenging to navigate with grep, so you need something that has properly parsed the code to help you find your way, especially when you are first learning the codebase.

**Comment by oschaaf** [comment]
https://github.com/oschaaf/envoy-perf-vscode has a VSCode workspace, which is what I mostly use to work on https://github.com/envoyproxy/envoy-perf/nighthawk (which uses Envoy as a submodule, and bazel to build).

Through that I got visually assisted gdb debugging, intellisense, clang-formatting, easier code navigation and generally a place to consolidate tids and bits as launch (and misc) tasks into the json config files for the project, as well as making DCO easier. Having a peek at it may be helpful; especially initially it helped greatly with discovering and learning about the Envoy project / codebase.  You do need the right plugins, e.g. I have been working with the official bazel integration plugin from the bazel team, and the C++ plugin from MS. 
To assist the IDE in best assisting you with intellisense and source code navigation, you may want to symlink some bazel-generated include directories so you can easily reference them in configuration (e.g. see https://github.com/oschaaf/envoy-perf-vscode/blob/master/.vscode/c_cpp_properties.json).  `symlink-ide-headers.sh` does this symlinking in my project.
