### ISSUE TITLE
create filter with external deps cryptopp

### ISSUE THREAD

**Issue by rbkumar88** [envoyproxy/envoy-filter-example#59]
Hi,

Do we have samples on how to add external deps on a filter using the bazel BUILD/WORKSPACE for eg., in my case I would like to add the crytopp dependency into my filter.

Thanks
Bharath

**Comment by htuch** [comment]
@rbkumar88 this is quite challenging for non-Bazel native builds, which it seems cryptopp is. You have basically three options:
1. Add your own `BUILD` files to build `cryptopp` under Bazel. You will need to own these and maintain them. Ideally you might be able to upstream them.
2. Do something similar to what we do in Envoy to build under either a genrule or repository rules, see https://github.com/envoyproxy/envoy/blob/master/bazel/repositories.bzl. This machinery is very complicated and I recommend this only for advanced Bazel hackers.
3. The Bazel team is working on native Bazel integration with external `cmake` and other C++ build systems. CC @irengrig.

**Comment by rbkumar88** [comment]
thanks @htuch . Will you be able to help on this. 
https://groups.google.com/forum/#!topic/envoy-users/uwjy1HwiBNE.  

P.S.,Running this behind a company proxy and have HTTP_PROXY and HTTPS_PROXY already set. Not sure this is because of proxy or something else.

**Comment by htuch** [comment]
@rbkumar88 I've replied to that thread. I'm going to close out this issue as I think the question is answered, please reopen if not.
