### ISSUE TITLE
Build is successful but test are failing with below exception

### ISSUE THREAD

**Issue by vpiduri** [envoyproxy/envoy-filter-example#60]
Thanks for all your help on this

gcc and g++ are below versions:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

DEBUG: /root/.cache/bazel/_bazel_root/cd764acb1d1bfad047ee8b5603f1640e/external/envoy/bazel/repositories.bzl:120:5: External dep build exited with return code: 0
INFO: Analysed target //:echo2_integration_test (36 packages loaded).
INFO: Found 1 test target...
ERROR: **/root/.cache/bazel/_bazel_root/cd764acb1d1bfad047ee8b5603f1640e/external/envoy/test/mocks/server/BUILD:11:1: C++ compilation of rule '@envoy//test/mocks/server:server_mocks' failed (Exit 4)**
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //:echo2_integration_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 390.112s, Critical Path: 128.84s
INFO: 39 processes: 39 linux-sandbox.

**Comment by htuch** [comment]
@vpiduri AFAICT, this is some legitimate compiler bug that you're experiencing. Does this occur if you switch to a newer gcc or clang? I'm going to close out this bug, since I think it's unrelated to anything Envoy specific, but feel free to continue this thread and/or reopen if you discover this is Envoy related.
