### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by DemantT** [envoyproxy/envoy-filter-example#61]
I build by bazel build //http-filter-example:envoy

ERROR: error loading package '': Extension file not found. Unable to load file '@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl': file doesn't exist or isn't a file
ERROR: error loading package '': Extension file not found. Unable to load file '@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl': file doesn't exist or isn't a file
INFO: Elapsed time: 0.069s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

anyone can help me？

**Comment by DemantT** [comment]
I build by  bazel build //http-filter-example:envoy

ERROR: error loading package '': Extension file not found. Unable to load file '@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl': file doesn't exist or isn't a file
ERROR: error loading package '': Extension file not found. Unable to load file '@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl': file doesn't exist or isn't a file
INFO: Elapsed time: 0.069s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

anyone can help me？

**Comment by htuch** [comment]
@DemantT this is probably due to https://github.com/envoyproxy/envoy/pull/4551. I will fix.
