### ISSUE TITLE
build error no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'

### ISSUE THREAD

**Issue by DemantT** [envoyproxy/envoy-filter-example#64]
I build it on MacOS.
I update code and build with "bazel build ://http-filter-example:envoy" Under the root directory  but failed...  err msg is :
make: *** [/private/var/tmp/_bazel_root/1aaa4e112752cd596b47f9795fb7a4b5/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep] Error 1
DEBUG: /private/var/tmp/_bazel_root/1aaa4e112752cd596b47f9795fb7a4b5/external/envoy/bazel/repositories.bzl:120:5: External dep build exited with return code: 2
DEBUG: /private/var/tmp/_bazel_root/1aaa4e112752cd596b47f9795fb7a4b5/external/envoy/bazel/repositories.bzl:122:9:  External dependency build failed, check above log for errors and ensure all prerequisites at https://github.com/envoyproxy/envoy/blob/master/bazel/README.md#quick-start-bazel-build-for-developers are met.
ERROR: /private/var/tmp/_bazel_root/1aaa4e112752cd596b47f9795fb7a4b5/external/envoy/bazel/repositories.bzl:271:13: no such package '@envoy_deps//': External dep build failed and referenced by '//external:tcmalloc_and_profiler'
ERROR: Analysis of target '//http-filter-example:envoy' failed; build aborted: Analysis failed
INFO: Elapsed time: 339.572s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded)

anyone can help me???

**Comment by swan-goose** [comment]
Hi,How did you solve your problem, I encountered the same problem

**Comment by swan-goose** [comment]
I found that someone solved it through ninja-build, but my installation did not solve it
