### ISSUE TITLE
question about the filter

### ISSUE THREAD

**Issue by DemantT** [envoyproxy/envoy-filter-example#65]
I want to add a filter, and by judging if the traffic is in order, if it is not satisfied, it will return directly to the back end. I want to know whether it should inherit from the treamDecoderFilter, and what can I do to stop the back end service，Like the state of the return code tatus or something

thank you

**Comment by dio** [comment]
Think you can do sendLocalReply, similar to this: https://github.com/dio/envoy-filter-diy/blob/master/source/extensions/filters/http/basic_auth/basic_auth.cc#L15

**Comment by DemantT** [comment]
@dio Thank you very much
