### ISSUE TITLE
http integration tests: Migrate c_str to getStringView

### ISSUE THREAD

**Issue by dio** [envoyproxy/envoy-filter-example#87]
As reported in: https://github.com/envoyproxy/envoy/issues/7082#issuecomment-497621734.

We can fix the issue by modifying https://github.com/envoyproxy/envoy-filter-example/blob/master/http-filter-example/http_filter_integration_test.cc#L39. And this PR https://github.com/envoyproxy/envoy/pull/6564 for inspiration. 

cc. @Satvindar

**Comment by Satvindar** [comment]
@dio, I have fixed this issue and build is successful now :)
 But when I am trying to create a PR, I am getting access denied error. I am sure I am missing some configuration before I push my changes to envoy git.  Can you help with the steps to follow for pushing my changes to envoy git? Thanks.

remote: Permission to envoyproxy/envoy-filter-example.git denied to Satvindar.
fatal: unable to access 'https://github.com/envoyproxy/envoy-filter-example.git/': The requested URL returned error: 403

**Comment by dio** [comment]
@Satvindar you need to work on your own fork. Please see e.g. this: https://gist.github.com/Chaser324/ce0505fbed06b947d962
